haircut/urls.py
from django.urls import path
from . import views 


app_name='haircut' 5

urlpatterns=[
    path("", views.home_page, name='home_page'), 
]

salon/urls.py
from django.contrib import admin 
from django.urls import path, include 

urlpatterns = [
	path(),
	path()
]

haircut/models.py
from django.db import models

# Create your models here.

haircut/views.py
from django.shortcuts import render

# Create your views here.
def home_page(request): 

    if request.method == 'POST':
        item = request.POST.get('item')   
        address=request.POST.get("address")
    
        return render(request, 'haircut/home_page.html', {'item': item, 'address': address}) 8 
    
    return render(request,‘haircut`/home_page.html’) 

haircut/templates/home_page.html
<!DOCTYPE html>
<html>
<head>
 <title>Amazing Amy’s Barbershop</title>
</head>
<body>
    <h1>Amazing Amy’s Barbershop</h1>
    <p>A Fresh Cut You for Your Family!</p>

    <!-- Item 1 -->
    <p>Hairstyling Services--Lisa: 50 RMB</p>
    <img src="http://tse4.mm.bing.net/th?id=OIP.YQIUdAV4MhxuX3x1HAs38wHaE8&w=232&h=160&c=7&o=5&pid=1.7">

    <!-- Item 2 -->
    <p> Haircut with Optional Color or Partial or Full Highlights-- Malinda : 55 RMB</p>
    <img src="http://tse4.mm.bing.net/th?id=OIP.hDfpzzW6C-cWMYbPjDn1jQHaHs&pid=Api">

    <!-- Item 3 --> 
    <p>Blowout of Choice or Hair-Extensions Blowout at Hair Fusion Bar-- Meghan: 40 RMB</p>
    <img src="http://tse2.mm.bing.net/th?id=OIP.ezWBu5OsI6FcaTDtSbS8CwHaKD&pid=Api">

    <!-- User Form -->
    <h1>submit your barber</h1>
    <form action="{% url 'haircut:home_page' %} " method="POST">
        {% csrf_token %}
        <input type="text" name="item" placeholder="the own customer’s name,"><br>
        <textarea placeholder="appointment time" name="appointment time"></textarea><br>
        <input type="submit" value="submit now!">
    </form>
    <h1>Your Order form</h1>
    <p>Item: {{time}}</p>
    <p>Address: {{address}}</p>

</body>
</html>